#En esta caso se usa postgre
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: sebas123 #En un entorno real esto se cambia por una variable de entorno
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mi_crud_simple_development

test:
  <<: *default
  database: mi_crud_simple_test

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  <<: *default
  database: mi_crud_simple_production
